"""Tests for Presentation Generator core module."""

import pytest
from presentation_gen.core import (
    build_prompt,
    load_config,
    get_formats,
    get_slide_templates,
    estimate_timing,
    export_to_markdown,
    generate_speaker_notes_only,
    FORMATS,
)


class TestBuildPrompt:
    def test_prompt_contains_topic(self):
        prompt = build_prompt("Machine Learning 101", 12, "beginners", "standard")
        assert "Machine Learning 101" in prompt

    def test_prompt_contains_slide_count(self):
        prompt = build_prompt("Topic", 15, "experts", "standard")
        assert "15" in prompt

    def test_prompt_contains_audience(self):
        prompt = build_prompt("Topic", 10, "executives", "keynote")
        assert "executives" in prompt

    def test_prompt_requests_speaker_notes(self):
        prompt = build_prompt("Topic", 10, "general", "standard")
        assert "Speaker Notes" in prompt


class TestTiming:
    def test_standard_timing(self):
        t = estimate_timing(12, "standard")
        assert t["total_seconds"] == 12 * 180
        assert t["total_minutes"] == 36.0

    def test_pecha_kucha_timing(self):
        t = estimate_timing(20, "pecha-kucha")
        assert t["total_seconds"] == 400

    def test_formatted_output(self):
        t = estimate_timing(10, "lightning")
        assert "m" in t["formatted"]


class TestConfig:
    def test_default_config(self):
        config = load_config()
        assert config["llm"]["temperature"] == 0.7

    def test_formats_exist(self):
        assert len(get_formats()) >= 4

    def test_slide_templates_exist(self):
        assert len(get_slide_templates()) >= 5


class TestExport:
    def test_export_markdown_has_header(self):
        md = export_to_markdown("# Slide 1\nContent", "My Topic")
        assert "My Topic" in md
        assert "Generated by" in md

    def test_speaker_notes_extraction(self):
        content = "### Slide 1: Intro\n**Speaker Notes:** This is a note.\n**Transition:** Next slide"
        notes = generate_speaker_notes_only(content)
        assert "note" in notes.lower() or "Slide 1" in notes
